# Config Map
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: springapp-configmap
data:
  # Configuration values can be set as key-value properties
  username: springapp
  password: mongodb@123
---
# Replication Controller for springapp
apiVersion: v1
kind: ReplicationController
metadata:
  name: spring-controller
spec:
  replicas: 1
  selector:
    app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: kubernet8s/spring-boot-mongo:tag
        imagePullPolicy: Always
        ports:
        - containerPort: 8080  
     
---
# Node Port Service For SpringApp
apiVersion: v1
kind: Service
metadata:
  name: springboot
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: springboot
---

